# -*- coding: utf-8 -*-
"""notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rrBXULE3il60UNw1yBNhxFSiushNK0JI
"""

import pandas as pd
import numpy as np
from ydata_profiling import ProfileReport

# from IPython.display import display
REPORT_PATH = "report/data_profiling_report.html"
DATASET_PATH = "data/raw/store_data.csv"
CLEAN_DATASET_PATH = "data/profiling/clean_store_data.csv"
# data profiling generate repport:

df = pd.read_csv(DATASET_PATH, sep=",", encoding="latin-1")
if not __import__("os").path.exists(REPORT_PATH):
    profile = ProfileReport(df, title="DataStore360 Raw Data Profiling Report", explorative=True)
    profile.to_file("report/data_profiling_report.html")

df.drop_duplicates(subset=["Row ID"], inplace=True)

duplicate_mask = df["Order ID"].duplicated(keep=False)

df["Panier"] = df.groupby("Order ID")["Product Name"].transform(lambda products: list(products))

df["Order Date"] = pd.to_datetime(df["Order Date"], format="mixed")
df["Ship Date"] = pd.to_datetime(df["Ship Date"], format="mixed")

invalid_date = df["Order Date"] > df["Ship Date"]
df["shipping_delay"] = df["Ship Date"] - df["Order Date"]
valid_delay = df.loc[~invalid_date, "shipping_delay"]
median_delay = valid_delay.median()
df.loc[invalid_date, "Ship Date"] = df.loc[invalid_date, "Order Date"] + median_delay

mode_ship_mode = df["Ship Mode"].mode()[0]
df["Ship Mode"] = df["Ship Mode"].fillna(mode_ship_mode)

df["Customer ID"] = df["Customer ID"].str.strip().str.upper()

freconcy_name = df["Customer Name"].mode()[0]
df["Customer Name"] = df["Customer Name"].fillna(freconcy_name)

category_corrections = {
    "Home Ofice": "Home Office",
    "Consumerr": "Consumer",
    "Corporrate": "Corporate",
}

df["Segment"] = df["Segment"].replace(category_corrections)

df["City"] = df["City"].astype("string").str.strip().str.lower().str.title()
df["State"] = df["City"].astype("string").str.strip().str.lower().str.title()

missing_postal = df["Postal Code"].isna()

postal_map_state = (
    df.dropna(subset=["Postal Code"]).groupby("State")["Postal Code"].agg(lambda x: x.mode()[0])
)

df.loc[missing_postal, "Postal Code"] = df.loc[missing_postal, "State"].map(postal_map_state)

# df["Product ID"].astype("string").str.match(r"^[A-Z]{3}-[A-Z]{2}-\d{8}$", na=False).sum()

categorys = {
    "furniture": "Furniture",
    "office supplies": "Office Supplies",
    "technology": "Technology",
}
df["Category"] = df["Category"].replace(categorys)

q1 = df["Sales"].quantile(0.25)
q3 = df["Sales"].quantile(0.75)

iqr = q3 - q1

lower = q1 - 1.5 * iqr
upper = q3 + 1.5 * iqr

outliers_mask = (df["Sales"] < lower) | (df["Sales"] > upper)

inliers = df.loc[~outliers_mask, "Sales"]

inliers_median = inliers.median()

df.loc[outliers_mask, "Sales"] = inliers_median

outlier_mask = df["Quantity"] < 0
inlier_quantity = df.loc[~outlier_mask, "Quantity"]
inlier_median = inlier_quantity.median()
df.loc[outlier_mask, "Quantity"] = inlier_median

q1 = df["Discount"].quantile(0.25)
q3 = df["Discount"].quantile(0.75)
iqr = q3 - q1

lower = q1 - 1.5 * iqr
upper = q3 + 1.5 * iqr

outliers_mask = (df["Discount"] < lower) | (df["Discount"] > upper)

inliers = df.loc[~outliers_mask, "Discount"]

inliers_median = inliers.median()

df.loc[outliers_mask, "Discount"] = inliers_median

q1 = df["Profit"].quantile(0.25)
q3 = df["Profit"].quantile(0.75)

iqr = q3 - q1

lower = q1 - 1.5 * iqr
upper = q3 + 1.5 * iqr

outliers_mask = (df["Profit"] < lower) | (df["Profit"] > upper)

inliers = df.loc[~outliers_mask, "Profit"]

inliers_median = inliers.median()

df.loc[outliers_mask, "Profit"] = inliers_median


invalid_discount_mask = df["Discount"] > 1.0

valid_discounts = df.loc[~invalid_discount_mask, "Discount"]
median_valid_discount = valid_discounts.median()

df.loc[invalid_discount_mask, "Discount"] = median_valid_discount


df["profit_margin"] = df["Profit"] / df["Sales"]

df["delivery_time"] = df["shipping_delay"].dt.days

# hashage:

df["Customer Name"] = df["Customer Name"].apply(
    lambda name: __import__("hashlib").sha256(name.encode("utf-8")).hexdigest()
)

# drop unessary use data
df.drop("Customer ID", axis=1, inplace=True)


# export clean data:
df.to_csv(
    CLEAN_DATASET_PATH,
    index=False,
    encoding="utf-8",
)
